import { useEffect, useMemo, useState } from 'react'

import { calculateMortgagePlan } from './lib/mortgage'

type SupportedLanguage = 'en' | 'it' | 'fr' | 'de'

type Translation = {
  pageTitle: string
  pageSubtitle: string
  languageLabel: string
  summaryTitle: string
  loanPrincipal: string
  monthlyPayment: string
  monthlyRateWithoutBankCost: string
  totalCapitalPaid: string
  totalInterest: string
  totalCapitalAndInterest: string
  totalBankCosts: string
  totalPaid: string
  showPlan: string
  hidePlan: string
  exportPlanAsPdf: string
  monthWithNumber: (month: number) => string
  payment: string
  principal: string
  interest: string
  bankCost: string
  remainingCapital: string
  planTotals: string
  capitalPaid: string
  interestPaid: string
  capitalPlusInterest: string
  selectedInputs: string
  chartTitle: string
  chartSubtitle: string
  yearLabel: string
  chartCapitalLegend: string
  chartInterestLegend: string
  houseCost: string
  downPayment: string
  mortgageDurationYears: string
  annualInterestRate: string
  annualInterestRateHint: string
  monthlyBankCost: string
  pdfTitle: string
  pdfGeneratedBy: string
  pdfHouseCost: string
  pdfDownPayment: string
  pdfDuration: string
  pdfYears: string
  pdfAnnualInterestRate: string
  pdfMonthlyBankCost: string
  pdfMonthlyPayment: string
  pdfTotalCapitalPaid: string
  pdfTotalInterestPaid: string
  pdfTotalCapitalAndInterest: string
  pdfTotalPaid: string
  pdfMonthHeader: string
  pdfPaymentHeader: string
  pdfPrincipalHeader: string
  pdfInterestHeader: string
  pdfBankCostHeader: string
  pdfRemainingCapitalHeader: string
  pdfTotalRow: string
}

const LOCALE_BY_LANGUAGE: Record<SupportedLanguage, string> = {
  en: 'en-US',
  it: 'it-IT',
  fr: 'fr-FR',
  de: 'de-DE',
}

const TRANSLATIONS: Record<SupportedLanguage, Translation> = {
  en: {
    pageTitle: 'Mortgage Calculator (French amortization)',
    pageSubtitle: 'Simulate your mortgage plan in euro. The monthly payment includes bank monthly costs.',
    languageLabel: 'Language',
    summaryTitle: 'Summary',
    loanPrincipal: 'Loan principal',
    monthlyPayment: 'Monthly payment',
    monthlyRateWithoutBankCost: 'Monthly rate (without bank cost)',
    totalCapitalPaid: 'Total capital paid',
    totalInterest: 'Total interest',
    totalCapitalAndInterest: 'Total capital + interest',
    totalBankCosts: 'Total bank costs',
    totalPaid: 'Total paid',
    showPlan: 'Show plan',
    hidePlan: 'Hide plan',
    exportPlanAsPdf: 'Export plan as PDF',
    monthWithNumber: (month: number) => `Month ${month}`,
    payment: 'Payment',
    principal: 'Principal',
    interest: 'Interest',
    bankCost: 'Bank cost',
    remainingCapital: 'Remaining capital',
    planTotals: 'Plan totals',
    capitalPaid: 'Capital paid',
    interestPaid: 'Interest paid',
    capitalPlusInterest: 'Capital + interest',
    selectedInputs: 'Selected inputs',
    chartTitle: 'Capital vs interest paid over time',
    chartSubtitle: 'Yearly totals across the mortgage duration',
    yearLabel: 'Year',
    chartCapitalLegend: 'Capital paid',
    chartInterestLegend: 'Interest paid',
    houseCost: 'House cost (€)',
    downPayment: 'Down payment (€)',
    mortgageDurationYears: 'Mortgage duration (years)',
    annualInterestRate: 'Annual interest rate',
    annualInterestRateHint: 'Default is 0.03 (3%)',
    monthlyBankCost: 'Monthly bank cost (€)',
    pdfTitle: 'Mortgage Plan',
    pdfGeneratedBy: 'Generated by Mortgage Calculator (French amortization)',
    pdfHouseCost: 'House cost',
    pdfDownPayment: 'Down payment',
    pdfDuration: 'Duration',
    pdfYears: 'years',
    pdfAnnualInterestRate: 'Annual interest rate',
    pdfMonthlyBankCost: 'Monthly bank cost',
    pdfMonthlyPayment: 'Monthly payment',
    pdfTotalCapitalPaid: 'Total capital paid',
    pdfTotalInterestPaid: 'Total interest paid',
    pdfTotalCapitalAndInterest: 'Total capital + interest',
    pdfTotalPaid: 'Total paid',
    pdfMonthHeader: 'Month',
    pdfPaymentHeader: 'Payment',
    pdfPrincipalHeader: 'Principal',
    pdfInterestHeader: 'Interest',
    pdfBankCostHeader: 'Bank cost',
    pdfRemainingCapitalHeader: 'Remaining capital',
    pdfTotalRow: 'TOTAL',
  },
  it: {
    pageTitle: 'Calcolatore Mutuo (Alla Francese)',
    pageSubtitle: 'Simula il piano del tuo mutuo in euro. La rata mensile include i costi bancari mensili.',
    languageLabel: 'Lingua',
    summaryTitle: 'Riepilogo',
    loanPrincipal: 'Capitale finanziato',
    monthlyPayment: 'Rata mensile',
    monthlyRateWithoutBankCost: 'Rata mensile (senza costo banca)',
    totalCapitalPaid: 'Totale capitale pagato',
    totalInterest: 'Totale interessi',
    totalCapitalAndInterest: 'Totale capitale + interessi',
    totalBankCosts: 'Totale costi bancari',
    totalPaid: 'Totale pagato',
    showPlan: 'Mostra piano',
    hidePlan: 'Nascondi piano',
    exportPlanAsPdf: 'Esporta piano in PDF',
    monthWithNumber: (month: number) => `Mese ${month}`,
    payment: 'Rata',
    principal: 'Capitale',
    interest: 'Interessi',
    bankCost: 'Costo banca',
    remainingCapital: 'Capitale residuo',
    planTotals: 'Totali piano',
    capitalPaid: 'Capitale pagato',
    interestPaid: 'Interessi pagati',
    capitalPlusInterest: 'Capitale + interessi',
    selectedInputs: 'Valori selezionati',
    chartTitle: 'Capitale vs interessi pagati nel tempo',
    chartSubtitle: 'Totali annuali lungo la durata del mutuo',
    yearLabel: 'Anno',
    chartCapitalLegend: 'Capitale pagato',
    chartInterestLegend: 'Interessi pagati',
    houseCost: 'Costo casa (€)',
    downPayment: 'Anticipo (€)',
    mortgageDurationYears: 'Durata mutuo (anni)',
    annualInterestRate: 'Tasso di interesse annuo',
    annualInterestRateHint: 'Valore predefinito 0.03 (3%)',
    monthlyBankCost: 'Costo banca mensile (€)',
    pdfTitle: 'Piano Mutuo',
    pdfGeneratedBy: 'Generato da Calcolatore Mutuo (Alla Francese)',
    pdfHouseCost: 'Costo casa',
    pdfDownPayment: 'Anticipo',
    pdfDuration: 'Durata',
    pdfYears: 'anni',
    pdfAnnualInterestRate: 'Tasso di interesse annuo',
    pdfMonthlyBankCost: 'Costo banca mensile',
    pdfMonthlyPayment: 'Rata mensile',
    pdfTotalCapitalPaid: 'Totale capitale pagato',
    pdfTotalInterestPaid: 'Totale interessi pagati',
    pdfTotalCapitalAndInterest: 'Totale capitale + interessi',
    pdfTotalPaid: 'Totale pagato',
    pdfMonthHeader: 'Mese',
    pdfPaymentHeader: 'Rata',
    pdfPrincipalHeader: 'Capitale',
    pdfInterestHeader: 'Interessi',
    pdfBankCostHeader: 'Costo banca',
    pdfRemainingCapitalHeader: 'Capitale residuo',
    pdfTotalRow: 'TOTALE',
  },
  fr: {
    pageTitle: 'Calculateur de Prêt Immobilier (amortissement à la française)',
    pageSubtitle:
      'Simulez votre plan de prêt en euros. La mensualité inclut les frais bancaires mensuels.',
    languageLabel: 'Langue',
    summaryTitle: 'Résumé',
    loanPrincipal: 'Capital emprunté',
    monthlyPayment: 'Mensualité',
    monthlyRateWithoutBankCost: 'Mensualité (hors frais bancaires)',
    totalCapitalPaid: 'Capital total remboursé',
    totalInterest: 'Intérêts totaux',
    totalCapitalAndInterest: 'Total capital + intérêts',
    totalBankCosts: 'Frais bancaires totaux',
    totalPaid: 'Total payé',
    showPlan: 'Afficher le plan',
    hidePlan: 'Masquer le plan',
    exportPlanAsPdf: 'Exporter le plan en PDF',
    monthWithNumber: (month: number) => `Mois ${month}`,
    payment: 'Paiement',
    principal: 'Capital',
    interest: 'Intérêt',
    bankCost: 'Frais bancaires',
    remainingCapital: 'Capital restant',
    planTotals: 'Totaux du plan',
    capitalPaid: 'Capital remboursé',
    interestPaid: 'Intérêts payés',
    capitalPlusInterest: 'Capital + intérêts',
    selectedInputs: 'Paramètres sélectionnés',
    chartTitle: 'Capital vs intérêts payés au fil du temps',
    chartSubtitle: 'Totaux annuels sur toute la durée du prêt',
    yearLabel: 'Année',
    chartCapitalLegend: 'Capital remboursé',
    chartInterestLegend: 'Intérêts payés',
    houseCost: 'Coût du logement (€)',
    downPayment: 'Apport (€)',
    mortgageDurationYears: 'Durée du prêt (années)',
    annualInterestRate: 'Taux d’intérêt annuel',
    annualInterestRateHint: 'Valeur par défaut: 0.03 (3%)',
    monthlyBankCost: 'Frais bancaires mensuels (€)',
    pdfTitle: 'Plan de Prêt',
    pdfGeneratedBy: 'Généré par Calculateur de Prêt Immobilier (amortissement à la française)',
    pdfHouseCost: 'Coût du logement',
    pdfDownPayment: 'Apport',
    pdfDuration: 'Durée',
    pdfYears: 'ans',
    pdfAnnualInterestRate: 'Taux d’intérêt annuel',
    pdfMonthlyBankCost: 'Frais bancaires mensuels',
    pdfMonthlyPayment: 'Mensualité',
    pdfTotalCapitalPaid: 'Capital total remboursé',
    pdfTotalInterestPaid: 'Intérêts totaux payés',
    pdfTotalCapitalAndInterest: 'Total capital + intérêts',
    pdfTotalPaid: 'Total payé',
    pdfMonthHeader: 'Mois',
    pdfPaymentHeader: 'Paiement',
    pdfPrincipalHeader: 'Capital',
    pdfInterestHeader: 'Intérêt',
    pdfBankCostHeader: 'Frais banque',
    pdfRemainingCapitalHeader: 'Capital restant',
    pdfTotalRow: 'TOTAL',
  },
  de: {
    pageTitle: 'Hypothekenrechner (französische Tilgung)',
    pageSubtitle:
      'Simulieren Sie Ihren Hypothekenplan in Euro. Die monatliche Rate enthält monatliche Bankkosten.',
    languageLabel: 'Sprache',
    summaryTitle: 'Zusammenfassung',
    loanPrincipal: 'Darlehensbetrag',
    monthlyPayment: 'Monatliche Rate',
    monthlyRateWithoutBankCost: 'Monatliche Rate (ohne Bankkosten)',
    totalCapitalPaid: 'Insgesamt gezahltes Kapital',
    totalInterest: 'Gesamtzinsen',
    totalCapitalAndInterest: 'Gesamtes Kapital + Zinsen',
    totalBankCosts: 'Gesamte Bankkosten',
    totalPaid: 'Insgesamt gezahlt',
    showPlan: 'Plan anzeigen',
    hidePlan: 'Plan ausblenden',
    exportPlanAsPdf: 'Plan als PDF exportieren',
    monthWithNumber: (month: number) => `Monat ${month}`,
    payment: 'Rate',
    principal: 'Kapital',
    interest: 'Zinsen',
    bankCost: 'Bankkosten',
    remainingCapital: 'Restkapital',
    planTotals: 'Plan-Summen',
    capitalPaid: 'Gezahltes Kapital',
    interestPaid: 'Gezahlte Zinsen',
    capitalPlusInterest: 'Kapital + Zinsen',
    selectedInputs: 'Ausgewählte Eingaben',
    chartTitle: 'Gezahltes Kapital vs. Zinsen im Zeitverlauf',
    chartSubtitle: 'Jährliche Summen über die gesamte Laufzeit',
    yearLabel: 'Jahr',
    chartCapitalLegend: 'Gezahltes Kapital',
    chartInterestLegend: 'Gezahlte Zinsen',
    houseCost: 'Immobilienpreis (€)',
    downPayment: 'Anzahlung (€)',
    mortgageDurationYears: 'Laufzeit (Jahre)',
    annualInterestRate: 'Jährlicher Zinssatz',
    annualInterestRateHint: 'Standardwert ist 0.03 (3%)',
    monthlyBankCost: 'Monatliche Bankkosten (€)',
    pdfTitle: 'Hypothekenplan',
    pdfGeneratedBy: 'Erstellt von Hypothekenrechner (französische Tilgung)',
    pdfHouseCost: 'Immobilienpreis',
    pdfDownPayment: 'Anzahlung',
    pdfDuration: 'Laufzeit',
    pdfYears: 'Jahre',
    pdfAnnualInterestRate: 'Jährlicher Zinssatz',
    pdfMonthlyBankCost: 'Monatliche Bankkosten',
    pdfMonthlyPayment: 'Monatliche Rate',
    pdfTotalCapitalPaid: 'Insgesamt gezahltes Kapital',
    pdfTotalInterestPaid: 'Insgesamt gezahlte Zinsen',
    pdfTotalCapitalAndInterest: 'Kapital + Zinsen gesamt',
    pdfTotalPaid: 'Insgesamt gezahlt',
    pdfMonthHeader: 'Monat',
    pdfPaymentHeader: 'Rate',
    pdfPrincipalHeader: 'Kapital',
    pdfInterestHeader: 'Zinsen',
    pdfBankCostHeader: 'Bankkosten',
    pdfRemainingCapitalHeader: 'Restkapital',
    pdfTotalRow: 'GESAMT',
  },
}

const SUPPORTED_LANGUAGES: SupportedLanguage[] = ['en', 'it', 'fr', 'de']

const getBrowserLanguage = (): SupportedLanguage => {
  if (typeof navigator === 'undefined') {
    return 'en'
  }

  const languageCandidates = [...navigator.languages, navigator.language]

  for (const candidate of languageCandidates) {
    const normalized = candidate.toLowerCase().split('-')[0]
    if (SUPPORTED_LANGUAGES.includes(normalized as SupportedLanguage)) {
      return normalized as SupportedLanguage
    }
  }

  return 'en'
}

const PAGE_LINE_LIMIT = 42

const toPdfSafeText = (value: string) =>
  value
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7e]/g, '?')

const formatCurrencyForPdf = (formatter: Intl.NumberFormat, amount: number) =>
  formatter.format(amount).replace('€', 'EUR').replace(/\u00a0/g, ' ')

const PDF_COLUMN_WIDTHS = {
  month: 6,
  payment: 14,
  principal: 14,
  interest: 14,
  bankCost: 14,
  remaining: 18,
} as const

const padPdfCell = (value: string, width: number, align: 'left' | 'right' = 'right') => {
  if (value.length >= width) {
    return value.slice(0, width)
  }

  return align === 'left' ? value.padEnd(width, ' ') : value.padStart(width, ' ')
}

const createPdfTableLine = (
  month: string,
  payment: string,
  principal: string,
  interest: string,
  bankCost: string,
  remainingCapital: string,
) =>
  [
    padPdfCell(month, PDF_COLUMN_WIDTHS.month, 'left'),
    padPdfCell(payment, PDF_COLUMN_WIDTHS.payment),
    padPdfCell(principal, PDF_COLUMN_WIDTHS.principal),
    padPdfCell(interest, PDF_COLUMN_WIDTHS.interest),
    padPdfCell(bankCost, PDF_COLUMN_WIDTHS.bankCost),
    padPdfCell(remainingCapital, PDF_COLUMN_WIDTHS.remaining),
  ].join(' | ')

function createPdfDocumentFromLines(lines: string[]) {
  const pages: string[][] = []
  for (let index = 0; index < lines.length; index += PAGE_LINE_LIMIT) {
    pages.push(lines.slice(index, index + PAGE_LINE_LIMIT))
  }

  const objects: Record<number, string> = {}
  const fontObjectId = 3
  const firstPageObjectId = 4

  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>'
  objects[2] = `<< /Type /Pages /Kids [${pages.map((_, pageIndex) => `${firstPageObjectId + pageIndex * 2} 0 R`).join(' ')}] /Count ${pages.length} >>`
  objects[fontObjectId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'

  pages.forEach((pageLines, pageIndex) => {
    const pageObjectId = firstPageObjectId + pageIndex * 2
    const contentObjectId = pageObjectId + 1

    const textOperations = pageLines.map((line) => `(${toPdfSafeText(line)}) Tj T*`).join('\n')
    const stream = `BT
/F1 10 Tf
40 560 Td
14 TL
${textOperations}
ET`

    objects[pageObjectId] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`
    objects[contentObjectId] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
  })

  const orderedObjectIds = Object.keys(objects)
    .map(Number)
    .sort((first, second) => first - second)

  let documentContent = '%PDF-1.4\n'
  const offsets: number[] = [0]

  orderedObjectIds.forEach((objectId) => {
    offsets[objectId] = documentContent.length
    documentContent += `${objectId} 0 obj\n${objects[objectId]}\nendobj\n`
  })

  const xrefStart = documentContent.length
  documentContent += `xref\n0 ${orderedObjectIds.length + 1}\n`
  documentContent += '0000000000 65535 f \n'
  orderedObjectIds.forEach((objectId) => {
    documentContent += `${offsets[objectId].toString().padStart(10, '0')} 00000 n \n`
  })
  documentContent += `trailer\n<< /Size ${orderedObjectIds.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`

  return new Blob([documentContent], { type: 'application/pdf' })
}

function App() {
  const [language, setLanguage] = useState<SupportedLanguage>(getBrowserLanguage)
  const [houseCost, setHouseCost] = useState(250000)
  const [downPayment, setDownPayment] = useState(50000)
  const [years, setYears] = useState(25)
  const [annualInterestRate, setAnnualInterestRate] = useState(0.03)
  const [monthlyBankCost, setMonthlyBankCost] = useState(0)
  const [showPlan, setShowPlan] = useState(false)

  const copy = TRANSLATIONS[language]

  const euroFormatter = useMemo(
    () =>
      new Intl.NumberFormat(LOCALE_BY_LANGUAGE[language], {
        style: 'currency',
        currency: 'EUR',
        maximumFractionDigits: 2,
      }),
    [language],
  )

  const pdfCurrencyFormatter = useMemo(
    () =>
      new Intl.NumberFormat(LOCALE_BY_LANGUAGE[language], {
        style: 'currency',
        currency: 'EUR',
        maximumFractionDigits: 2,
      }),
    [language],
  )

  const plan = useMemo(
    () =>
      calculateMortgagePlan({
        houseCost,
        downPayment,
        years,
        annualInterestRate,
        monthlyBankCost,
      }),
    [annualInterestRate, downPayment, houseCost, monthlyBankCost, years],
  )

  const yearlyBreakdown = useMemo(() => {
    const totalsByYear = new Map<number, { principal: number; interest: number }>()

    plan.installments.forEach((installment) => {
      const year = Math.ceil(installment.month / 12)
      const currentYear = totalsByYear.get(year) ?? { principal: 0, interest: 0 }
      currentYear.principal += installment.principal
      currentYear.interest += installment.interest
      totalsByYear.set(year, currentYear)
    })

    return Array.from(totalsByYear.entries())
      .sort(([firstYear], [secondYear]) => firstYear - secondYear)
      .map(([year, totals]) => ({
        year,
        principal: totals.principal,
        interest: totals.interest,
      }))
  }, [plan.installments])

  const maxYearlyAmount = useMemo(
    () => Math.max(...yearlyBreakdown.map((bucket) => Math.max(bucket.principal, bucket.interest)), 0),
    [yearlyBreakdown],
  )

  const handleExportPlanAsPdf = () => {
    const lines = [
      copy.pdfTitle,
      copy.pdfGeneratedBy,
      '',
      `${copy.pdfHouseCost}: ${formatCurrencyForPdf(pdfCurrencyFormatter, houseCost)}`,
      `${copy.pdfDownPayment}: ${formatCurrencyForPdf(pdfCurrencyFormatter, downPayment)}`,
      `${copy.pdfDuration}: ${years} ${copy.pdfYears}`,
      `${copy.pdfAnnualInterestRate}: ${(annualInterestRate * 100).toFixed(2)}%`,
      `${copy.pdfMonthlyBankCost}: ${formatCurrencyForPdf(pdfCurrencyFormatter, monthlyBankCost)}`,
      `${copy.pdfMonthlyPayment}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.monthlyPayment)}`,
      `${copy.pdfTotalCapitalPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalPaid)}`,
      `${copy.pdfTotalInterestPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalInterest)}`,
      `${copy.pdfTotalCapitalAndInterest}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalAndInterest)}`,
      `${copy.pdfTotalPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalPaid)}`,
      '',
      createPdfTableLine(
        copy.pdfMonthHeader,
        copy.pdfPaymentHeader,
        copy.pdfPrincipalHeader,
        copy.pdfInterestHeader,
        copy.pdfBankCostHeader,
        copy.pdfRemainingCapitalHeader,
      ),
      '-'.repeat(91),
      ...plan.installments.map(
        (installment) =>
          createPdfTableLine(
            installment.month.toString(),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.payment),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.principal),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.interest),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.bankCost),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.remainingPrincipal),
          ),
      ),
      '-'.repeat(91),
      createPdfTableLine(
        copy.pdfTotalRow,
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalPaid),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalPaid),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalInterest),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalBankCosts),
        formatCurrencyForPdf(pdfCurrencyFormatter, 0),
      ),
    ]

    const pdfBlob = createPdfDocumentFromLines(lines)
    const pdfDownloadUrl = URL.createObjectURL(pdfBlob)
    const linkElement = document.createElement('a')
    linkElement.href = pdfDownloadUrl
    linkElement.download = `mortgage-plan-${new Date().toISOString().slice(0, 10)}.pdf`
    linkElement.click()
    URL.revokeObjectURL(pdfDownloadUrl)
  }

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-100 sm:px-6 lg:px-8">
      <section className="mx-auto w-full max-w-5xl">
        <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{copy.pageTitle}</h1>
        <p className="mt-2 text-sm text-slate-300 sm:text-base">{copy.pageSubtitle}</p>

        <div className="mt-4 w-full max-w-sm">
          <label className="block" htmlFor="language">
            <span className="text-sm font-medium text-slate-200">{copy.languageLabel}</span>
            <select
              id="language"
              value={language}
              onChange={(event) => setLanguage(event.target.value as SupportedLanguage)}
              className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none ring-emerald-400 focus:ring"
            >
              <option value="en">English</option>
              <option value="it">Italiano</option>
              <option value="fr">Français</option>
              <option value="de">Deutsch</option>
            </select>
          </label>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]">
          <form className="space-y-4 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:p-5">
            <InputField
              id="houseCost"
              label={copy.houseCost}
              value={houseCost}
              min={0}
              step={10000}
              onValueChange={setHouseCost}
            />
            <InputField
              id="downPayment"
              label={copy.downPayment}
              value={downPayment}
              min={0}
              step={1000}
              onValueChange={setDownPayment}
            />
            <InputField
              id="years"
              label={copy.mortgageDurationYears}
              value={years}
              min={1}
              step={1}
              onValueChange={setYears}
            />
            <InputField
              id="annualInterestRate"
              label={copy.annualInterestRate}
              value={annualInterestRate}
              min={0}
              max={1}
              step={0.001}
              onValueChange={setAnnualInterestRate}
              hint={copy.annualInterestRateHint}
            />
            <InputField
              id="monthlyBankCost"
              label={copy.monthlyBankCost}
              value={monthlyBankCost}
              min={0}
              step={1}
              onValueChange={setMonthlyBankCost}
            />
          </form>

          <div className="rounded-xl border border-slate-800 bg-slate-900 p-4 sm:p-5">
            <h2 className="text-lg font-semibold">{copy.summaryTitle}</h2>
            <dl className="mt-4 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
              <SummaryItem label={copy.loanPrincipal} value={euroFormatter.format(plan.principal)} />
              <SummaryItem label={copy.monthlyPayment} value={euroFormatter.format(plan.monthlyPayment)} />
              <SummaryItem
                label={copy.monthlyRateWithoutBankCost}
                value={euroFormatter.format(plan.monthlyRateWithoutBankCost)}
              />
              <SummaryItem label={copy.totalCapitalPaid} value={euroFormatter.format(plan.totalCapitalPaid)} />
              <SummaryItem label={copy.totalInterest} value={euroFormatter.format(plan.totalInterest)} />
              <SummaryItem label={copy.totalCapitalAndInterest} value={euroFormatter.format(plan.totalCapitalAndInterest)} />
              <SummaryItem label={copy.totalBankCosts} value={euroFormatter.format(plan.totalBankCosts)} />
              <SummaryItem label={copy.totalPaid} value={euroFormatter.format(plan.totalPaid)} />
            </dl>

            <div className="mt-6 rounded-lg border border-slate-700 bg-slate-950/60 p-4">
              <h3 className="text-base font-semibold text-slate-100">{copy.selectedInputs}</h3>
              <dl className="mt-3 grid grid-cols-1 gap-2 text-sm sm:grid-cols-2">
                <SummaryItem label={copy.houseCost} value={euroFormatter.format(houseCost)} />
                <SummaryItem label={copy.downPayment} value={euroFormatter.format(downPayment)} />
                <SummaryItem label={copy.mortgageDurationYears} value={`${years}`} />
                <SummaryItem label={copy.annualInterestRate} value={`${(annualInterestRate * 100).toFixed(2)}%`} />
                <SummaryItem label={copy.monthlyBankCost} value={euroFormatter.format(monthlyBankCost)} />
              </dl>
            </div>

            <div className="mt-6 rounded-lg border border-slate-700 bg-slate-950/60 p-4">
              <h3 className="text-base font-semibold text-slate-100">{copy.chartTitle}</h3>
              <p className="mt-1 text-xs text-slate-400">{copy.chartSubtitle}</p>

              <div className="mt-4 space-y-3">
                {yearlyBreakdown.map((bucket) => {
                  const principalWidth = maxYearlyAmount === 0 ? 0 : (bucket.principal / maxYearlyAmount) * 100
                  const interestWidth = maxYearlyAmount === 0 ? 0 : (bucket.interest / maxYearlyAmount) * 100

                  return (
                    <div key={bucket.year} className="rounded-md border border-slate-800 bg-slate-900/80 p-3">
                      <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">
                        {copy.yearLabel} {bucket.year}
                      </p>
                      <div className="mt-2 grid gap-2">
                        <div>
                          <div className="mb-1 flex items-center justify-between text-xs">
                            <span className="text-emerald-300">{copy.chartCapitalLegend}</span>
                            <span className="font-medium text-slate-100">{euroFormatter.format(bucket.principal)}</span>
                          </div>
                          <div className="h-2 rounded-full bg-slate-800">
                            <div
                              className="h-2 rounded-full bg-emerald-500"
                              style={{ width: `${principalWidth}%` }}
                              aria-label={`${copy.chartCapitalLegend} ${copy.yearLabel} ${bucket.year}`}
                            />
                          </div>
                        </div>

                        <div>
                          <div className="mb-1 flex items-center justify-between text-xs">
                            <span className="text-cyan-300">{copy.chartInterestLegend}</span>
                            <span className="font-medium text-slate-100">{euroFormatter.format(bucket.interest)}</span>
                          </div>
                          <div className="h-2 rounded-full bg-slate-800">
                            <div
                              className="h-2 rounded-full bg-cyan-500"
                              style={{ width: `${interestWidth}%` }}
                              aria-label={`${copy.chartInterestLegend} ${copy.yearLabel} ${bucket.year}`}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>

            <div className="mt-5 flex flex-wrap gap-3">
              <button
                type="button"
                onClick={() => setShowPlan((current) => !current)}
                className="rounded-md bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-emerald-400"
              >
                {showPlan ? copy.hidePlan : copy.showPlan}
              </button>
              <button
                type="button"
                onClick={handleExportPlanAsPdf}
                className="rounded-md border border-emerald-400 px-4 py-2 text-sm font-semibold text-emerald-300 transition hover:bg-emerald-500/10"
              >
                {copy.exportPlanAsPdf}
              </button>
            </div>

            {showPlan ? (
              <ul className="mt-5 space-y-3">
                {plan.installments.map((installment) => (
                  <li
                    key={installment.month}
                    className="rounded-lg border border-slate-700 bg-slate-950/60 p-3 text-xs sm:text-sm"
                  >
                    <p className="font-semibold text-emerald-300">{copy.monthWithNumber(installment.month)}</p>
                    <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
                      <PlanValue label={copy.payment} value={euroFormatter.format(installment.payment)} />
                      <PlanValue label={copy.principal} value={euroFormatter.format(installment.principal)} />
                      <PlanValue label={copy.interest} value={euroFormatter.format(installment.interest)} />
                      <PlanValue label={copy.bankCost} value={euroFormatter.format(installment.bankCost)} />
                      <PlanValue label={copy.remainingCapital} value={euroFormatter.format(installment.remainingPrincipal)} />
                    </div>
                  </li>
                ))}
              </ul>
            ) : null}

            {showPlan ? (
              <div className="mt-5 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm">
                <h3 className="text-base font-semibold text-emerald-200">{copy.planTotals}</h3>
                <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-3">
                  <PlanValue label={copy.capitalPaid} value={euroFormatter.format(plan.totalCapitalPaid)} />
                  <PlanValue label={copy.interestPaid} value={euroFormatter.format(plan.totalInterest)} />
                  <PlanValue label={copy.capitalPlusInterest} value={euroFormatter.format(plan.totalCapitalAndInterest)} />
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </section>
    </main>
  )
}

type InputFieldProps = {
  id: string
  label: string
  value: number
  min?: number
  max?: number
  step?: number
  hint?: string
  onValueChange: (value: number) => void
}

function InputField({ id, label, value, min, max, step, hint, onValueChange }: InputFieldProps) {
  const [draftValue, setDraftValue] = useState(value.toString())
  const [isFocused, setIsFocused] = useState(false)

  useEffect(() => {
    if (!isFocused) {
      setDraftValue(value.toString())
    }
  }, [isFocused, value])

  const commitValue = (rawValue: string) => {
    if (rawValue === '') {
      onValueChange(0)
      return
    }

    const parsedValue = Number(rawValue)

    if (Number.isNaN(parsedValue)) {
      return
    }

    onValueChange(parsedValue)
  }

  const formatDraftValue = (rawValue: string) => {
    if (rawValue === '') {
      return '0'
    }

    return rawValue
  }

  const handleStepChange = (direction: 'increase' | 'decrease') => {
    const increment = step ?? 1
    const parsedDraftValue = Number(draftValue)
    const baseValue = Number.isNaN(parsedDraftValue) ? value : parsedDraftValue
    const nextValue = direction === 'increase' ? baseValue + increment : baseValue - increment
    const clampedValue = Math.max(min ?? Number.NEGATIVE_INFINITY, Math.min(max ?? Number.POSITIVE_INFINITY, nextValue))
    onValueChange(clampedValue)
    setDraftValue(clampedValue.toString())
  }

  return (
    <label className="block" htmlFor={id}>
      <span className="text-sm font-medium text-slate-200">{label}</span>
      <div className="mt-1 flex gap-2">
        <button
          type="button"
          onClick={() => handleStepChange('decrease')}
          className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-lg font-semibold text-slate-100 transition hover:border-emerald-400 hover:text-emerald-300"
          aria-label={`Decrease ${label}`}
        >
          −
        </button>
        <input
          id={id}
          type="number"
          className="w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none ring-emerald-400 focus:ring"
          value={formatDraftValue(draftValue)}
          min={min}
          max={max}
          step={step}
          onFocus={() => {
            setIsFocused(true)
            if (draftValue === '0') {
              setDraftValue('')
            }
          }}
          onBlur={() => {
            setIsFocused(false)
            if (draftValue === '') {
              setDraftValue('0')
            }
          }}
          onChange={(event) => {
            const rawInput = event.target.value
            setDraftValue(rawInput)
            commitValue(rawInput)
          }}
        />
        <button
          type="button"
          onClick={() => handleStepChange('increase')}
          className="rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-lg font-semibold text-slate-100 transition hover:border-emerald-400 hover:text-emerald-300"
          aria-label={`Increase ${label}`}
        >
          +
        </button>
      </div>
      {hint ? <span className="mt-1 block text-xs text-slate-400">{hint}</span> : null}
    </label>
  )
}

function SummaryItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-slate-700 bg-slate-950/60 p-3">
      <dt className="text-slate-400">{label}</dt>
      <dd className="mt-1 font-semibold text-slate-100">{value}</dd>
    </div>
  )
}

function PlanValue({ label, value }: { label: string; value: string }) {
  return (
    <p>
      <span className="text-slate-400">{label}: </span>
      <span className="font-medium text-slate-100">{value}</span>
    </p>
  )
}

export default App
