import { useEffect, useMemo, useRef, useState, type PointerEvent } from 'react'

import { calculateMortgagePlan, type AdditionalPaymentStrategy } from './lib/mortgage'

type SupportedLanguage = 'en' | 'it' | 'fr' | 'de'

type Translation = {
  pageTitle: string
  pageSubtitle: string
  languageLabel: string
  summaryTitle: string
  loanPrincipal: string
  monthlyPayment: string
  monthlyRateWithoutBankCost: string
  totalCapitalPaid: string
  totalInterest: string
  totalCapitalAndInterest: string
  totalBankCosts: string
  totalPaid: string
  showPlan: string
  hidePlan: string
  exportPlanAsPdf: string
  monthWithNumber: (month: number) => string
  payment: string
  principal: string
  interest: string
  bankCost: string
  additionalPayment: string
  remainingCapital: string
  planTotals: string
  capitalPaid: string
  interestPaid: string
  capitalPlusInterest: string
  chartTitle: string
  chartSubtitle: string
  yearLabel: string
  chartReimbursedCapitalLegend: string
  chartRemainingCapitalLegend: string
  chartInterestLegend: string
  houseCost: string
  downPayment: string
  mortgageDurationYears: string
  annualInterestRate: string
  annualInterestRateHint: string
  monthlyBankCost: string
  additionalAnnualPayment: string
  downPaymentExceedsHouseCostError: string
  additionalPaymentExceedsLoanError: string
  additionalPaymentStrategy: string
  shortenDurationStrategy: string
  reduceMonthlyPaymentStrategy: string
  totalAdditionalPayments: string
  interestSaved: string
  durationSaved: string
  pdfTitle: string
  pdfGeneratedBy: string
  pdfHouseCost: string
  pdfDownPayment: string
  pdfDuration: string
  pdfYears: string
  pdfAnnualInterestRate: string
  pdfMonthlyBankCost: string
  pdfAdditionalAnnualPayment: string
  pdfAdditionalPaymentStrategy: string
  pdfTotalAdditionalPayments: string
  pdfInterestSaved: string
  pdfDurationSaved: string
  pdfMonthlyPayment: string
  pdfTotalCapitalPaid: string
  pdfTotalInterestPaid: string
  pdfTotalCapitalAndInterest: string
  pdfTotalPaid: string
  pdfMonthHeader: string
  pdfPaymentHeader: string
  pdfPrincipalHeader: string
  pdfInterestHeader: string
  pdfBankCostHeader: string
  pdfAdditionalPaymentHeader: string
  pdfRemainingCapitalHeader: string
  pdfTotalRow: string
}

const EURO_NUMBER_LOCALE = 'de-DE'

const TRANSLATIONS: Record<SupportedLanguage, Translation> = {
  en: {
    pageTitle: 'Mortgage Calculator (French amortization)',
    pageSubtitle: 'Simulate your mortgage plan in euro. The monthly payment includes bank monthly costs.',
    languageLabel: 'Language',
    summaryTitle: 'Summary',
    loanPrincipal: 'Loan principal',
    monthlyPayment: 'Monthly payment',
    monthlyRateWithoutBankCost: 'Monthly rate (without bank cost)',
    totalCapitalPaid: 'Total capital paid',
    totalInterest: 'Total interest',
    totalCapitalAndInterest: 'Total capital + interest',
    totalBankCosts: 'Total bank costs',
    totalPaid: 'Total paid',
    showPlan: 'Show plan',
    hidePlan: 'Hide plan',
    exportPlanAsPdf: 'Export plan as PDF',
    monthWithNumber: (month: number) => `Month ${month}`,
    payment: 'Payment',
    principal: 'Principal',
    interest: 'Interest',
    bankCost: 'Bank cost',
    additionalPayment: 'Additional payment',
    remainingCapital: 'Remaining capital',
    planTotals: 'Plan totals',
    capitalPaid: 'Capital paid',
    interestPaid: 'Interest paid',
    capitalPlusInterest: 'Capital + interest',
    chartTitle: 'Capital vs interest paid over time',
    chartSubtitle: 'Use the slider to inspect values over time',
    yearLabel: 'Year',
    chartReimbursedCapitalLegend: 'Reimbursed capital',
    chartRemainingCapitalLegend: 'Remaining capital',
    chartInterestLegend: 'Paid interest',
    houseCost: 'House cost (€)',
    downPayment: 'Down payment (€)',
    mortgageDurationYears: 'Mortgage duration (years)',
    annualInterestRate: 'Annual interest rate',
    annualInterestRateHint: 'Default is 3,00%',
    monthlyBankCost: 'Monthly bank cost (€)',
    additionalAnnualPayment: 'Additional annual payment (€)',
    downPaymentExceedsHouseCostError: 'Down payment cannot be higher than house cost.',
    additionalPaymentExceedsLoanError: 'Additional annual payment cannot exceed the loan principal (house cost - down payment).',
    additionalPaymentStrategy: 'Additional payment strategy',
    shortenDurationStrategy: 'Shorten mortgage duration',
    reduceMonthlyPaymentStrategy: 'Reduce monthly payment',
    totalAdditionalPayments: 'Total additional payments',
    interestSaved: 'Interest saved vs no extra payments',
    durationSaved: 'Duration saved',
    pdfTitle: 'Mortgage Plan',
    pdfGeneratedBy: 'Generated by Mortgage Calculator (French amortization)',
    pdfHouseCost: 'House cost',
    pdfDownPayment: 'Down payment',
    pdfDuration: 'Duration',
    pdfYears: 'years',
    pdfAnnualInterestRate: 'Annual interest rate',
    pdfMonthlyBankCost: 'Monthly bank cost',
    pdfAdditionalAnnualPayment: 'Additional annual payment',
    pdfAdditionalPaymentStrategy: 'Additional payment strategy',
    pdfTotalAdditionalPayments: 'Total additional payments',
    pdfInterestSaved: 'Interest saved vs no extra payments',
    pdfDurationSaved: 'Duration saved',
    pdfMonthlyPayment: 'Monthly payment',
    pdfTotalCapitalPaid: 'Total capital paid',
    pdfTotalInterestPaid: 'Total interest paid',
    pdfTotalCapitalAndInterest: 'Total capital + interest',
    pdfTotalPaid: 'Total paid',
    pdfMonthHeader: 'Month',
    pdfPaymentHeader: 'Payment',
    pdfPrincipalHeader: 'Principal',
    pdfInterestHeader: 'Interest',
    pdfBankCostHeader: 'Bank cost',
    pdfAdditionalPaymentHeader: 'Additional payment',
    pdfRemainingCapitalHeader: 'Remaining capital',
    pdfTotalRow: 'TOTAL',
  },
  it: {
    pageTitle: 'Calcolatore Mutuo (Alla Francese)',
    pageSubtitle: 'Simula il piano del tuo mutuo in euro. La rata mensile include i costi bancari mensili.',
    languageLabel: 'Lingua',
    summaryTitle: 'Riepilogo',
    loanPrincipal: 'Capitale finanziato',
    monthlyPayment: 'Rata mensile',
    monthlyRateWithoutBankCost: 'Rata mensile (senza costo banca)',
    totalCapitalPaid: 'Totale capitale pagato',
    totalInterest: 'Totale interessi',
    totalCapitalAndInterest: 'Totale capitale + interessi',
    totalBankCosts: 'Totale costi bancari',
    totalPaid: 'Totale pagato',
    showPlan: 'Mostra piano',
    hidePlan: 'Nascondi piano',
    exportPlanAsPdf: 'Esporta piano in PDF',
    monthWithNumber: (month: number) => `Mese ${month}`,
    payment: 'Rata',
    principal: 'Capitale',
    interest: 'Interessi',
    bankCost: 'Costo banca',
    additionalPayment: 'Pagamento extra',
    remainingCapital: 'Capitale residuo',
    planTotals: 'Totali piano',
    capitalPaid: 'Capitale pagato',
    interestPaid: 'Interessi pagati',
    capitalPlusInterest: 'Capitale + interessi',
    chartTitle: 'Capitale vs interessi pagati nel tempo',
    chartSubtitle: 'Usa il cursore per vedere i valori nel tempo',
    yearLabel: 'Anno',
    chartReimbursedCapitalLegend: 'Capitale rimborsato',
    chartRemainingCapitalLegend: 'Capitale residuo',
    chartInterestLegend: 'Interessi pagati',
    houseCost: 'Costo casa (€)',
    downPayment: 'Anticipo (€)',
    mortgageDurationYears: 'Durata mutuo (anni)',
    annualInterestRate: 'Tasso di interesse annuo',
    annualInterestRateHint: 'Valore predefinito 3,00%',
    monthlyBankCost: 'Costo banca mensile (€)',
    additionalAnnualPayment: 'Pagamento annuale extra (€)',
    downPaymentExceedsHouseCostError: "L'anticipo non può essere maggiore del costo casa.",
    additionalPaymentExceedsLoanError:
      'Il pagamento annuale extra non può superare il capitale finanziato (costo casa - anticipo).',
    additionalPaymentStrategy: 'Strategia pagamento extra',
    shortenDurationStrategy: 'Riduci durata mutuo',
    reduceMonthlyPaymentStrategy: 'Riduci rata mensile',
    totalAdditionalPayments: 'Totale pagamenti extra',
    interestSaved: 'Interessi risparmiati vs nessun extra',
    durationSaved: 'Durata risparmiata',
    pdfTitle: 'Piano Mutuo',
    pdfGeneratedBy: 'Generato da Calcolatore Mutuo (Alla Francese)',
    pdfHouseCost: 'Costo casa',
    pdfDownPayment: 'Anticipo',
    pdfDuration: 'Durata',
    pdfYears: 'anni',
    pdfAnnualInterestRate: 'Tasso di interesse annuo',
    pdfMonthlyBankCost: 'Costo banca mensile',
    pdfAdditionalAnnualPayment: 'Pagamento annuale extra',
    pdfAdditionalPaymentStrategy: 'Strategia pagamento extra',
    pdfTotalAdditionalPayments: 'Totale pagamenti extra',
    pdfInterestSaved: 'Interessi risparmiati vs nessun extra',
    pdfDurationSaved: 'Durata risparmiata',
    pdfMonthlyPayment: 'Rata mensile',
    pdfTotalCapitalPaid: 'Totale capitale pagato',
    pdfTotalInterestPaid: 'Totale interessi pagati',
    pdfTotalCapitalAndInterest: 'Totale capitale + interessi',
    pdfTotalPaid: 'Totale pagato',
    pdfMonthHeader: 'Mese',
    pdfPaymentHeader: 'Rata',
    pdfPrincipalHeader: 'Capitale',
    pdfInterestHeader: 'Interessi',
    pdfBankCostHeader: 'Costo banca',
    pdfAdditionalPaymentHeader: 'Pagamento extra',
    pdfRemainingCapitalHeader: 'Capitale residuo',
    pdfTotalRow: 'TOTALE',
  },
  fr: {
    pageTitle: 'Calculateur de Prêt Immobilier (amortissement à la française)',
    pageSubtitle:
      'Simulez votre plan de prêt en euros. La mensualité inclut les frais bancaires mensuels.',
    languageLabel: 'Langue',
    summaryTitle: 'Résumé',
    loanPrincipal: 'Capital emprunté',
    monthlyPayment: 'Mensualité',
    monthlyRateWithoutBankCost: 'Mensualité (hors frais bancaires)',
    totalCapitalPaid: 'Capital total remboursé',
    totalInterest: 'Intérêts totaux',
    totalCapitalAndInterest: 'Total capital + intérêts',
    totalBankCosts: 'Frais bancaires totaux',
    totalPaid: 'Total payé',
    showPlan: 'Afficher le plan',
    hidePlan: 'Masquer le plan',
    exportPlanAsPdf: 'Exporter le plan en PDF',
    monthWithNumber: (month: number) => `Mois ${month}`,
    payment: 'Paiement',
    principal: 'Capital',
    interest: 'Intérêt',
    bankCost: 'Frais bancaires',
    additionalPayment: 'Paiement supplémentaire',
    remainingCapital: 'Capital restant',
    planTotals: 'Totaux du plan',
    capitalPaid: 'Capital remboursé',
    interestPaid: 'Intérêts payés',
    capitalPlusInterest: 'Capital + intérêts',
    chartTitle: 'Capital vs intérêts payés au fil du temps',
    chartSubtitle: 'Utilisez le curseur pour inspecter les valeurs dans le temps',
    yearLabel: 'Année',
    chartReimbursedCapitalLegend: 'Capital remboursé',
    chartRemainingCapitalLegend: 'Capital restant',
    chartInterestLegend: 'Intérêts payés',
    houseCost: 'Coût du logement (€)',
    downPayment: 'Apport (€)',
    mortgageDurationYears: 'Durée du prêt (années)',
    annualInterestRate: 'Taux d’intérêt annuel',
    annualInterestRateHint: 'Valeur par défaut : 3,00%',
    monthlyBankCost: 'Frais bancaires mensuels (€)',
    additionalAnnualPayment: 'Paiement annuel supplémentaire (€)',
    downPaymentExceedsHouseCostError: "L'apport ne peut pas être supérieur au coût du logement.",
    additionalPaymentExceedsLoanError:
      "Le paiement annuel supplémentaire ne peut pas dépasser le capital emprunté (coût du logement - apport).",
    additionalPaymentStrategy: 'Stratégie paiement supplémentaire',
    shortenDurationStrategy: 'Réduire la durée du prêt',
    reduceMonthlyPaymentStrategy: 'Réduire la mensualité',
    totalAdditionalPayments: 'Total paiements supplémentaires',
    interestSaved: 'Intérêts économisés vs sans suppléments',
    durationSaved: 'Durée économisée',
    pdfTitle: 'Plan de Prêt',
    pdfGeneratedBy: 'Généré par Calculateur de Prêt Immobilier (amortissement à la française)',
    pdfHouseCost: 'Coût du logement',
    pdfDownPayment: 'Apport',
    pdfDuration: 'Durée',
    pdfYears: 'ans',
    pdfAnnualInterestRate: 'Taux d’intérêt annuel',
    pdfMonthlyBankCost: 'Frais bancaires mensuels',
    pdfAdditionalAnnualPayment: 'Paiement annuel supplémentaire',
    pdfAdditionalPaymentStrategy: 'Stratégie paiement supplémentaire',
    pdfTotalAdditionalPayments: 'Total paiements supplémentaires',
    pdfInterestSaved: 'Intérêts économisés vs sans suppléments',
    pdfDurationSaved: 'Durée économisée',
    pdfMonthlyPayment: 'Mensualité',
    pdfTotalCapitalPaid: 'Capital total remboursé',
    pdfTotalInterestPaid: 'Intérêts totaux payés',
    pdfTotalCapitalAndInterest: 'Total capital + intérêts',
    pdfTotalPaid: 'Total payé',
    pdfMonthHeader: 'Mois',
    pdfPaymentHeader: 'Paiement',
    pdfPrincipalHeader: 'Capital',
    pdfInterestHeader: 'Intérêt',
    pdfBankCostHeader: 'Frais banque',
    pdfAdditionalPaymentHeader: 'Paiement supplémentaire',
    pdfRemainingCapitalHeader: 'Capital restant',
    pdfTotalRow: 'TOTAL',
  },
  de: {
    pageTitle: 'Hypothekenrechner (französische Tilgung)',
    pageSubtitle:
      'Simulieren Sie Ihren Hypothekenplan in Euro. Die monatliche Rate enthält monatliche Bankkosten.',
    languageLabel: 'Sprache',
    summaryTitle: 'Zusammenfassung',
    loanPrincipal: 'Darlehensbetrag',
    monthlyPayment: 'Monatliche Rate',
    monthlyRateWithoutBankCost: 'Monatliche Rate (ohne Bankkosten)',
    totalCapitalPaid: 'Insgesamt gezahltes Kapital',
    totalInterest: 'Gesamtzinsen',
    totalCapitalAndInterest: 'Gesamtes Kapital + Zinsen',
    totalBankCosts: 'Gesamte Bankkosten',
    totalPaid: 'Insgesamt gezahlt',
    showPlan: 'Plan anzeigen',
    hidePlan: 'Plan ausblenden',
    exportPlanAsPdf: 'Plan als PDF exportieren',
    monthWithNumber: (month: number) => `Monat ${month}`,
    payment: 'Rate',
    principal: 'Kapital',
    interest: 'Zinsen',
    bankCost: 'Bankkosten',
    additionalPayment: 'Zusatzzahlung',
    remainingCapital: 'Restkapital',
    planTotals: 'Plan-Summen',
    capitalPaid: 'Gezahltes Kapital',
    interestPaid: 'Gezahlte Zinsen',
    capitalPlusInterest: 'Kapital + Zinsen',
    chartTitle: 'Gezahltes Kapital vs. Zinsen im Zeitverlauf',
    chartSubtitle: 'Verwenden Sie den Schieberegler, um Werte im Zeitverlauf zu sehen',
    yearLabel: 'Jahr',
    chartReimbursedCapitalLegend: 'Getilgtes Kapital',
    chartRemainingCapitalLegend: 'Restkapital',
    chartInterestLegend: 'Gezahlte Zinsen',
    houseCost: 'Immobilienpreis (€)',
    downPayment: 'Anzahlung (€)',
    mortgageDurationYears: 'Laufzeit (Jahre)',
    annualInterestRate: 'Jährlicher Zinssatz',
    annualInterestRateHint: 'Standardwert ist 3,00%',
    monthlyBankCost: 'Monatliche Bankkosten (€)',
    additionalAnnualPayment: 'Zusätzliche jährliche Zahlung (€)',
    downPaymentExceedsHouseCostError: 'Die Anzahlung darf nicht höher als der Immobilienpreis sein.',
    additionalPaymentExceedsLoanError:
      'Die zusätzliche jährliche Zahlung darf den Darlehensbetrag (Immobilienpreis - Anzahlung) nicht übersteigen.',
    additionalPaymentStrategy: 'Strategie für Zusatzzahlung',
    shortenDurationStrategy: 'Laufzeit verkürzen',
    reduceMonthlyPaymentStrategy: 'Monatsrate senken',
    totalAdditionalPayments: 'Gesamte Zusatzzahlungen',
    interestSaved: 'Gesparte Zinsen vs ohne Zusatzzahlungen',
    durationSaved: 'Gesparte Laufzeit',
    pdfTitle: 'Hypothekenplan',
    pdfGeneratedBy: 'Erstellt von Hypothekenrechner (französische Tilgung)',
    pdfHouseCost: 'Immobilienpreis',
    pdfDownPayment: 'Anzahlung',
    pdfDuration: 'Laufzeit',
    pdfYears: 'Jahre',
    pdfAnnualInterestRate: 'Jährlicher Zinssatz',
    pdfMonthlyBankCost: 'Monatliche Bankkosten',
    pdfAdditionalAnnualPayment: 'Zusätzliche jährliche Zahlung',
    pdfAdditionalPaymentStrategy: 'Strategie für Zusatzzahlung',
    pdfTotalAdditionalPayments: 'Gesamte Zusatzzahlungen',
    pdfInterestSaved: 'Gesparte Zinsen vs ohne Zusatzzahlungen',
    pdfDurationSaved: 'Gesparte Laufzeit',
    pdfMonthlyPayment: 'Monatliche Rate',
    pdfTotalCapitalPaid: 'Insgesamt gezahltes Kapital',
    pdfTotalInterestPaid: 'Insgesamt gezahlte Zinsen',
    pdfTotalCapitalAndInterest: 'Kapital + Zinsen gesamt',
    pdfTotalPaid: 'Insgesamt gezahlt',
    pdfMonthHeader: 'Monat',
    pdfPaymentHeader: 'Rate',
    pdfPrincipalHeader: 'Kapital',
    pdfInterestHeader: 'Zinsen',
    pdfBankCostHeader: 'Bankkosten',
    pdfAdditionalPaymentHeader: 'Zusatzzahlung',
    pdfRemainingCapitalHeader: 'Restkapital',
    pdfTotalRow: 'GESAMT',
  },
}

const SUPPORTED_LANGUAGES: SupportedLanguage[] = ['en', 'it', 'fr', 'de']

const getBrowserLanguage = (): SupportedLanguage => {
  if (typeof navigator === 'undefined') {
    return 'en'
  }

  const languageCandidates = [...navigator.languages, navigator.language]

  for (const candidate of languageCandidates) {
    const normalized = candidate.toLowerCase().split('-')[0]
    if (SUPPORTED_LANGUAGES.includes(normalized as SupportedLanguage)) {
      return normalized as SupportedLanguage
    }
  }

  return 'en'
}

const PAGE_LINE_LIMIT = 42

const toPdfSafeText = (value: string) =>
  value
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/[^\x20-\x7e]/g, '?')

const formatCurrencyForPdf = (formatter: Intl.NumberFormat, amount: number) =>
  formatter.format(amount).replace('€', 'EUR').replace(/\u00a0/g, ' ')

const PDF_COLUMN_WIDTHS = {
  month: 6,
  payment: 12,
  principal: 12,
  interest: 12,
  bankCost: 10,
  additionalPayment: 12,
  remaining: 14,
} as const

const padPdfCell = (value: string, width: number, align: 'left' | 'right' = 'right') => {
  if (value.length >= width) {
    return value.slice(0, width)
  }

  return align === 'left' ? value.padEnd(width, ' ') : value.padStart(width, ' ')
}

const createPdfTableLine = (
  month: string,
  payment: string,
  principal: string,
  interest: string,
  bankCost: string,
  additionalPayment: string,
  remainingCapital: string,
) =>
  [
    padPdfCell(month, PDF_COLUMN_WIDTHS.month, 'left'),
    padPdfCell(payment, PDF_COLUMN_WIDTHS.payment),
    padPdfCell(principal, PDF_COLUMN_WIDTHS.principal),
    padPdfCell(interest, PDF_COLUMN_WIDTHS.interest),
    padPdfCell(bankCost, PDF_COLUMN_WIDTHS.bankCost),
    padPdfCell(additionalPayment, PDF_COLUMN_WIDTHS.additionalPayment),
    padPdfCell(remainingCapital, PDF_COLUMN_WIDTHS.remaining),
  ].join(' | ')

function createPdfDocumentFromLines(lines: string[]) {
  const pages: string[][] = []
  for (let index = 0; index < lines.length; index += PAGE_LINE_LIMIT) {
    pages.push(lines.slice(index, index + PAGE_LINE_LIMIT))
  }

  const objects: Record<number, string> = {}
  const fontObjectId = 3
  const firstPageObjectId = 4

  objects[1] = '<< /Type /Catalog /Pages 2 0 R >>'
  objects[2] = `<< /Type /Pages /Kids [${pages.map((_, pageIndex) => `${firstPageObjectId + pageIndex * 2} 0 R`).join(' ')}] /Count ${pages.length} >>`
  objects[fontObjectId] = '<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>'

  pages.forEach((pageLines, pageIndex) => {
    const pageObjectId = firstPageObjectId + pageIndex * 2
    const contentObjectId = pageObjectId + 1

    const textOperations = pageLines.map((line) => `(${toPdfSafeText(line)}) Tj T*`).join('\n')
    const stream = `BT
/F1 10 Tf
40 560 Td
14 TL
${textOperations}
ET`

    objects[pageObjectId] =
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`
    objects[contentObjectId] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
  })

  const orderedObjectIds = Object.keys(objects)
    .map(Number)
    .sort((first, second) => first - second)

  let documentContent = '%PDF-1.4\n'
  const offsets: number[] = [0]

  orderedObjectIds.forEach((objectId) => {
    offsets[objectId] = documentContent.length
    documentContent += `${objectId} 0 obj\n${objects[objectId]}\nendobj\n`
  })

  const xrefStart = documentContent.length
  documentContent += `xref\n0 ${orderedObjectIds.length + 1}\n`
  documentContent += '0000000000 65535 f \n'
  orderedObjectIds.forEach((objectId) => {
    documentContent += `${offsets[objectId].toString().padStart(10, '0')} 00000 n \n`
  })
  documentContent += `trailer\n<< /Size ${orderedObjectIds.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`

  return new Blob([documentContent], { type: 'application/pdf' })
}

function App() {
  const [language, setLanguage] = useState<SupportedLanguage>(getBrowserLanguage)
  const [houseCost, setHouseCost] = useState(250000)
  const [downPayment, setDownPayment] = useState(50000)
  const [years, setYears] = useState(25)
  const [annualInterestRate, setAnnualInterestRate] = useState(3)
  const [monthlyBankCost, setMonthlyBankCost] = useState(0)
  const [additionalAnnualPayment, setAdditionalAnnualPayment] = useState(0)
  const [additionalPaymentStrategy, setAdditionalPaymentStrategy] =
    useState<AdditionalPaymentStrategy>('shorten-duration')
  const [showPlan, setShowPlan] = useState(false)
  const [selectedChartYear, setSelectedChartYear] = useState(0)

  const copy = TRANSLATIONS[language]

  const euroFormatter = useMemo(
    () =>
      new Intl.NumberFormat(EURO_NUMBER_LOCALE, {
        style: 'currency',
        currency: 'EUR',
        maximumFractionDigits: 2,
      }),
    [],
  )

  const pdfCurrencyFormatter = useMemo(
    () =>
      new Intl.NumberFormat(EURO_NUMBER_LOCALE, {
        style: 'currency',
        currency: 'EUR',
        maximumFractionDigits: 2,
      }),
    [],
  )

  const plan = useMemo(
    () =>
      calculateMortgagePlan({
        houseCost,
        downPayment,
        years,
        annualInterestRate: annualInterestRate / 100,
        monthlyBankCost,
        additionalAnnualPayment,
        additionalPaymentStrategy,
      }),
    [additionalAnnualPayment, additionalPaymentStrategy, annualInterestRate, downPayment, houseCost, monthlyBankCost, years],
  )

  const baselinePlan = useMemo(
    () =>
      calculateMortgagePlan({
        houseCost,
        downPayment,
        years,
        annualInterestRate: annualInterestRate / 100,
        monthlyBankCost,
        additionalAnnualPayment: 0,
      }),
    [annualInterestRate, downPayment, houseCost, monthlyBankCost, years],
  )

  const chartData = useMemo(() => {
    let reimbursedCapital = 0
    let paidInterest = 0

    const chartYears = Math.ceil(plan.installments.length / 12)
    const points = [
      {
        year: 0,
        remainingCapital: plan.principal,
        reimbursedCapital: 0,
        paidInterest: 0,
      },
    ]

    for (let index = 0; index < chartYears; index += 1) {
      const year = index + 1
      const yearStart = index * 12
      const yearEnd = Math.min((index + 1) * 12, plan.installments.length)
      const yearInstallments = plan.installments.slice(yearStart, yearEnd)
      const installmentIndex = Math.min(yearEnd, plan.installments.length) - 1
      const installment = plan.installments[Math.max(installmentIndex, 0)]

      reimbursedCapital += yearInstallments.reduce((sum, currentInstallment) => sum + currentInstallment.principal, 0)
      paidInterest += yearInstallments.reduce((sum, currentInstallment) => sum + currentInstallment.interest, 0)

      points.push({
        year,
        remainingCapital: installment?.remainingPrincipal ?? 0,
        reimbursedCapital,
        paidInterest,
      })
    }

    return points
  }, [plan.installments, plan.principal])

  useEffect(() => {
    if (selectedChartYear > chartData.length - 1) {
      setSelectedChartYear(chartData.length - 1)
    }
  }, [chartData.length, selectedChartYear])

  const maxChartAmount = useMemo(
    () =>
      Math.max(
        ...chartData.map((point) => Math.max(point.remainingCapital, point.reimbursedCapital, point.paidInterest)),
        0,
      ),
    [chartData],
  )

  const selectedChartPoint = chartData[Math.max(selectedChartYear, 0)] ?? null
  const interestSaved = Math.max(baselinePlan.totalInterest - plan.totalInterest, 0)
  const monthsSaved = Math.max(baselinePlan.durationMonths - plan.durationMonths, 0)
  const loanPrincipal = Math.max(houseCost - downPayment, 0)
  const validationError =
    downPayment > houseCost
      ? copy.downPaymentExceedsHouseCostError
      : additionalAnnualPayment > loanPrincipal
        ? copy.additionalPaymentExceedsLoanError
        : null

  const handleExportPlanAsPdf = () => {
    if (validationError) {
      return
    }

    const lines = [
      copy.pdfTitle,
      copy.pdfGeneratedBy,
      '',
      `${copy.pdfHouseCost}: ${formatCurrencyForPdf(pdfCurrencyFormatter, houseCost)}`,
      `${copy.pdfDownPayment}: ${formatCurrencyForPdf(pdfCurrencyFormatter, downPayment)}`,
      `${copy.pdfDuration}: ${years} ${copy.pdfYears}`,
      `${copy.pdfAnnualInterestRate}: ${annualInterestRate.toFixed(2).replace('.', ',')}%`,
      `${copy.pdfMonthlyBankCost}: ${formatCurrencyForPdf(pdfCurrencyFormatter, monthlyBankCost)}`,
      `${copy.pdfAdditionalAnnualPayment}: ${formatCurrencyForPdf(pdfCurrencyFormatter, additionalAnnualPayment)}`,
      `${copy.pdfAdditionalPaymentStrategy}: ${
        additionalPaymentStrategy === 'shorten-duration'
          ? copy.shortenDurationStrategy
          : copy.reduceMonthlyPaymentStrategy
      }`,
      `${copy.pdfMonthlyPayment}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.monthlyPayment)}`,
      `${copy.pdfTotalCapitalPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalPaid)}`,
      `${copy.pdfTotalInterestPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalInterest)}`,
      `${copy.pdfTotalAdditionalPayments}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalAdditionalPayments)}`,
      `${copy.pdfInterestSaved}: ${formatCurrencyForPdf(pdfCurrencyFormatter, interestSaved)}`,
      `${copy.pdfDurationSaved}: ${Math.floor(monthsSaved / 12)}y ${monthsSaved % 12}m`,
      `${copy.pdfTotalCapitalAndInterest}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalAndInterest)}`,
      `${copy.pdfTotalPaid}: ${formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalPaid)}`,
      '',
      createPdfTableLine(
        copy.pdfMonthHeader,
        copy.pdfPaymentHeader,
        copy.pdfPrincipalHeader,
        copy.pdfInterestHeader,
        copy.pdfBankCostHeader,
        copy.pdfAdditionalPaymentHeader,
        copy.pdfRemainingCapitalHeader,
      ),
      '-'.repeat(92),
      ...plan.installments.map(
        (installment) =>
          createPdfTableLine(
            installment.month.toString(),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.payment),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.principal),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.interest),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.bankCost),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.additionalPayment),
            formatCurrencyForPdf(pdfCurrencyFormatter, installment.remainingPrincipal),
          ),
      ),
      '-'.repeat(92),
      createPdfTableLine(
        copy.pdfTotalRow,
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalPaid),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalCapitalPaid),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalInterest),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalBankCosts),
        formatCurrencyForPdf(pdfCurrencyFormatter, plan.totalAdditionalPayments),
        formatCurrencyForPdf(pdfCurrencyFormatter, 0),
      ),
    ]

    const pdfBlob = createPdfDocumentFromLines(lines)
    const pdfDownloadUrl = URL.createObjectURL(pdfBlob)
    const linkElement = document.createElement('a')
    linkElement.href = pdfDownloadUrl
    linkElement.download = `mortgage-plan-${new Date().toISOString().slice(0, 10)}.pdf`
    linkElement.click()
    URL.revokeObjectURL(pdfDownloadUrl)
  }

  return (
    <main className="min-h-screen bg-slate-950 px-4 py-8 text-slate-100 sm:px-6 lg:px-8">
      <section className="mx-auto w-full max-w-5xl">
        <h1 className="text-2xl font-bold tracking-tight sm:text-3xl">{copy.pageTitle}</h1>
        <p className="mt-2 text-sm text-slate-300 sm:text-base">{copy.pageSubtitle}</p>

        <div className="mt-4 w-full max-w-sm">
          <label className="block" htmlFor="language">
            <span className="text-sm font-medium text-slate-200">{copy.languageLabel}</span>
            <select
              id="language"
              value={language}
              onChange={(event) => setLanguage(event.target.value as SupportedLanguage)}
              className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none ring-emerald-400 focus:ring"
            >
              <option value="en">English</option>
              <option value="it">Italiano</option>
              <option value="fr">Français</option>
              <option value="de">Deutsch</option>
            </select>
          </label>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[320px_1fr]">
          <form className="space-y-4 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:p-5">
            <InputField
              id="houseCost"
              label={copy.houseCost}
              value={houseCost}
              min={0}
              step={5000}
              onValueChange={setHouseCost}
              useGrouping
            />
            <InputField
              id="downPayment"
              label={copy.downPayment}
              value={downPayment}
              min={0}
              step={1000}
              onValueChange={setDownPayment}
              useGrouping
            />
            {downPayment > houseCost ? (
              <p className="text-sm font-medium text-rose-400">{copy.downPaymentExceedsHouseCostError}</p>
            ) : null}
            <InputField
              id="years"
              label={copy.mortgageDurationYears}
              value={years}
              min={1}
              step={1}
              onValueChange={setYears}
            />
            <InputField
              id="annualInterestRate"
              label={copy.annualInterestRate}
              value={annualInterestRate}
              min={0}
              max={100}
              step={0.01}
              fractionDigits={2}
              onValueChange={setAnnualInterestRate}
              hint={copy.annualInterestRateHint}
            />
            <InputField
              id="monthlyBankCost"
              label={copy.monthlyBankCost}
              value={monthlyBankCost}
              min={0}
              step={1}
              onValueChange={setMonthlyBankCost}
              useGrouping
              fractionDigits={2}
            />
            <InputField
              id="additionalAnnualPayment"
              label={copy.additionalAnnualPayment}
              value={additionalAnnualPayment}
              min={0}
              step={100}
              onValueChange={setAdditionalAnnualPayment}
              useGrouping
            />
            {additionalAnnualPayment > loanPrincipal ? (
              <p className="text-sm font-medium text-rose-400">{copy.additionalPaymentExceedsLoanError}</p>
            ) : null}
            <label className="block" htmlFor="additionalPaymentStrategy">
              <span className="text-sm font-medium text-slate-200">{copy.additionalPaymentStrategy}</span>
              <select
                id="additionalPaymentStrategy"
                value={additionalPaymentStrategy}
                onChange={(event) => setAdditionalPaymentStrategy(event.target.value as AdditionalPaymentStrategy)}
                className="mt-1 w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none ring-emerald-400 focus:ring"
              >
                <option value="shorten-duration">{copy.shortenDurationStrategy}</option>
                <option value="reduce-payment">{copy.reduceMonthlyPaymentStrategy}</option>
              </select>
            </label>
          </form>

          <div className="rounded-xl border border-slate-800 bg-slate-900 p-4 sm:p-5">
            <h2 className="text-lg font-semibold">{copy.summaryTitle}</h2>
            {validationError ? (
              <p className="mt-4 rounded-md border border-rose-500/60 bg-rose-500/10 px-3 py-2 text-sm text-rose-300">
                {validationError}
              </p>
            ) : null}
            <dl className="mt-4 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
              <SummaryItem label={copy.loanPrincipal} value={euroFormatter.format(plan.principal)} />
              <SummaryItem label={copy.monthlyPayment} value={euroFormatter.format(plan.monthlyPayment)} />
              <SummaryItem
                label={copy.monthlyRateWithoutBankCost}
                value={euroFormatter.format(plan.monthlyRateWithoutBankCost)}
              />
              <SummaryItem label={copy.totalCapitalPaid} value={euroFormatter.format(plan.totalCapitalPaid)} />
              <SummaryItem label={copy.totalInterest} value={euroFormatter.format(plan.totalInterest)} />
              <SummaryItem label={copy.totalAdditionalPayments} value={euroFormatter.format(plan.totalAdditionalPayments)} />
              <SummaryItem label={copy.totalCapitalAndInterest} value={euroFormatter.format(plan.totalCapitalAndInterest)} />
              <SummaryItem label={copy.totalBankCosts} value={euroFormatter.format(plan.totalBankCosts)} />
              <SummaryItem label={copy.totalPaid} value={euroFormatter.format(plan.totalPaid)} />
              {additionalAnnualPayment > 0 && !validationError ? (
                <>
                  <SummaryItem label={copy.interestSaved} value={euroFormatter.format(interestSaved)} />
                  <SummaryItem
                    label={copy.durationSaved}
                    value={`${Math.floor(monthsSaved / 12)}y ${monthsSaved % 12}m`}
                  />
                </>
              ) : null}
            </dl>

            <div className="mt-6 rounded-lg border border-slate-700 bg-slate-950/60 p-4">
              <h3 className="text-base font-semibold text-slate-100">{copy.chartTitle}</h3>
              <p className="mt-1 text-xs text-slate-400">{copy.chartSubtitle}</p>

              {chartData.length > 0 && !validationError ? (
                <>
                  <InteractiveChart
                    data={chartData}
                    maxAmount={maxChartAmount}
                    selectedYear={selectedChartYear}
                    onYearChange={setSelectedChartYear}
                  />

                  {selectedChartPoint ? (
                    <div className="mt-4 grid gap-2 text-sm sm:grid-cols-3">
                      <ChartLegendValue
                        colorClassName="bg-violet-400"
                        label={`${copy.chartRemainingCapitalLegend} (${copy.yearLabel} ${selectedChartPoint.year})`}
                        value={euroFormatter.format(selectedChartPoint.remainingCapital)}
                      />
                      <ChartLegendValue
                        colorClassName="bg-emerald-400"
                        label={`${copy.chartReimbursedCapitalLegend} (${copy.yearLabel} ${selectedChartPoint.year})`}
                        value={euroFormatter.format(selectedChartPoint.reimbursedCapital)}
                      />
                      <ChartLegendValue
                        colorClassName="bg-cyan-400"
                        label={`${copy.chartInterestLegend} (${copy.yearLabel} ${selectedChartPoint.year})`}
                        value={euroFormatter.format(selectedChartPoint.paidInterest)}
                      />
                    </div>
                  ) : null}
                </>
              ) : null}
            </div>

            <div className="mt-5 flex flex-wrap gap-3">
              <button
                type="button"
                onClick={() => setShowPlan((current) => !current)}
                disabled={Boolean(validationError)}
                className="rounded-md bg-emerald-500 px-4 py-2 text-sm font-semibold text-slate-900 transition hover:bg-emerald-400"
              >
                {showPlan ? copy.hidePlan : copy.showPlan}
              </button>
              <button
                type="button"
                onClick={handleExportPlanAsPdf}
                disabled={Boolean(validationError)}
                className="rounded-md border border-emerald-400 px-4 py-2 text-sm font-semibold text-emerald-300 transition hover:bg-emerald-500/10"
              >
                {copy.exportPlanAsPdf}
              </button>
            </div>

            {showPlan && !validationError ? (
              <ul className="mt-5 space-y-3">
                {plan.installments.map((installment) => (
                  <li
                    key={installment.month}
                    className="rounded-lg border border-slate-700 bg-slate-950/60 p-3 text-xs sm:text-sm"
                  >
                    <p className="font-semibold text-emerald-300">{copy.monthWithNumber(installment.month)}</p>
                    <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
                      <PlanValue label={copy.payment} value={euroFormatter.format(installment.payment)} />
                      <PlanValue label={copy.principal} value={euroFormatter.format(installment.principal)} />
                      <PlanValue label={copy.interest} value={euroFormatter.format(installment.interest)} />
                      <PlanValue label={copy.bankCost} value={euroFormatter.format(installment.bankCost)} />
                      <PlanValue
                        label={copy.additionalPayment}
                        value={euroFormatter.format(installment.additionalPayment)}
                      />
                      <PlanValue label={copy.remainingCapital} value={euroFormatter.format(installment.remainingPrincipal)} />
                    </div>
                  </li>
                ))}
              </ul>
            ) : null}

            {showPlan && !validationError ? (
              <div className="mt-5 rounded-lg border border-emerald-500/30 bg-emerald-500/5 p-4 text-sm">
                <h3 className="text-base font-semibold text-emerald-200">{copy.planTotals}</h3>
                <div className="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-3">
                  <PlanValue label={copy.capitalPaid} value={euroFormatter.format(plan.totalCapitalPaid)} />
                  <PlanValue label={copy.interestPaid} value={euroFormatter.format(plan.totalInterest)} />
                  <PlanValue label={copy.totalAdditionalPayments} value={euroFormatter.format(plan.totalAdditionalPayments)} />
                  <PlanValue label={copy.capitalPlusInterest} value={euroFormatter.format(plan.totalCapitalAndInterest)} />
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </section>
    </main>
  )
}

type ChartPoint = {
  year: number
  remainingCapital: number
  reimbursedCapital: number
  paidInterest: number
}

type InteractiveChartProps = {
  data: ChartPoint[]
  maxAmount: number
  selectedYear: number
  onYearChange: (year: number) => void
}

function InteractiveChart({ data, maxAmount, selectedYear, onYearChange }: InteractiveChartProps) {
  const width = 1200
  const height = 650
  const padding = { top: 20, right: 24, bottom: 40, left: 112 }
  const innerWidth = width - padding.left - padding.right
  const innerHeight = height - padding.top - padding.bottom
  const xStep = data.length > 1 ? innerWidth / (data.length - 1) : 0
  const maxYear = data[data.length - 1]?.year ?? 0
  const yTicks = 4
  const xTickStep = useMemo(() => {
    if (maxYear <= 6) {
      return 1
    }

    const rawStep = maxYear / 6
    const possibleSteps = [1, 2, 5, 10, 15, 20, 25, 30]
    return possibleSteps.find((step) => step >= rawStep) ?? possibleSteps[possibleSteps.length - 1]
  }, [maxYear])
  const xTicks = useMemo(() => {
    const ticks = [0]

    for (let year = xTickStep; year <= maxYear; year += xTickStep) {
      ticks.push(year)
    }

    if (ticks[ticks.length - 1] !== maxYear) {
      ticks.push(maxYear)
    }

    return ticks
  }, [maxYear, xTickStep])
  const yAxisFormatter = useMemo(
    () =>
      new Intl.NumberFormat(EURO_NUMBER_LOCALE, {
        maximumFractionDigits: 1,
      }),
    [],
  )

  const xForIndex = (index: number) => padding.left + index * xStep
  const xForYear = (year: number) =>
    maxYear === 0 ? padding.left : padding.left + (year / maxYear) * innerWidth
  const yForValue = (value: number) => {
    if (maxAmount <= 0) {
      return padding.top + innerHeight
    }

    return padding.top + innerHeight - (value / maxAmount) * innerHeight
  }

  const linePath = (extractor: (point: ChartPoint) => number) =>
    data
      .map((point, index) => `${index === 0 ? 'M' : 'L'} ${xForIndex(index)} ${yForValue(extractor(point))}`)
      .join(' ')

  return (
    <div className="mt-4 rounded-md border border-slate-800 bg-slate-900/80 p-2 sm:p-3">
      <svg
        viewBox={`0 0 ${width} ${height}`}
        className="h-[250px] w-full"
        role="img"
        aria-label="Mortgage capital and interest chart"
      >
        <line
          x1={padding.left}
          y1={padding.top + innerHeight}
          x2={padding.left + innerWidth}
          y2={padding.top + innerHeight}
          className="stroke-slate-600"
        />
        <line x1={padding.left} y1={padding.top} x2={padding.left} y2={padding.top + innerHeight} className="stroke-slate-600" />

        <path d={linePath((point) => point.remainingCapital)} fill="none" className="stroke-violet-400" strokeWidth={2.5} />
        <path d={linePath((point) => point.reimbursedCapital)} fill="none" className="stroke-emerald-400" strokeWidth={2.5} />
        <path d={linePath((point) => point.paidInterest)} fill="none" className="stroke-cyan-400" strokeWidth={2.5} />

        {Array.from({ length: yTicks + 1 }, (_, index) => {
          const tickValue = (maxAmount / yTicks) * index
          const y = yForValue(tickValue)

          return (
            <g key={`y-tick-${index}`}>
              <line x1={padding.left - 6} y1={y} x2={padding.left} y2={y} className="stroke-slate-500" />
              <text x={padding.left - 12} y={y + 6} className="fill-slate-400 text-[20px]" textAnchor="end">
                {`${yAxisFormatter.format(tickValue / 1000)} K`}
              </text>
            </g>
          )
        })}

        {xTicks.map((tickYear) => (
          <text
            key={`x-tick-${tickYear}`}
            x={xForYear(tickYear)}
            y={padding.top + innerHeight + 34}
            className="fill-slate-400 text-[20px]"
            textAnchor="middle"
          >
            {tickYear}
          </text>
        ))}

        {selectedYear >= 0 && selectedYear < data.length ? (
          <>
            <line
              x1={xForIndex(selectedYear)}
              y1={padding.top}
              x2={xForIndex(selectedYear)}
              y2={padding.top + innerHeight}
              className="stroke-slate-300"
              strokeDasharray="4 4"
            />
            <circle cx={xForIndex(selectedYear)} cy={yForValue(data[selectedYear].remainingCapital)} r={4} className="fill-violet-300" />
            <circle cx={xForIndex(selectedYear)} cy={yForValue(data[selectedYear].reimbursedCapital)} r={4} className="fill-emerald-300" />
            <circle cx={xForIndex(selectedYear)} cy={yForValue(data[selectedYear].paidInterest)} r={4} className="fill-cyan-300" />
          </>
        ) : null}
      </svg>
      <div className="mt-3 px-1">
        <input
          type="range"
          min={0}
          max={Math.max(data.length - 1, 0)}
          step={1}
          value={Math.min(Math.max(selectedYear, 0), Math.max(data.length - 1, 0))}
          onChange={(event) => onYearChange(Number(event.target.value))}
          aria-label="Select chart year"
          className="h-2 w-full cursor-pointer accent-emerald-400"
        />
      </div>
    </div>
  )
}

type InputFieldProps = {
  id: string
  label: string
  value: number
  min?: number
  max?: number
  step?: number
  hint?: string
  fractionDigits?: number
  useGrouping?: boolean
  onValueChange: (value: number) => void
}

const LONG_PRESS_INITIAL_DELAY_MS = 400
const LONG_PRESS_REPEAT_INTERVAL_MS = 120

const parseEuropeanNumber = (rawValue: string): number => {
  const normalized = rawValue
    .replace(/\./g, '')
    .replace(/\s/g, '')
    .replace(',', '.')
  return Number(normalized)
}

const countFractionDigits = (stepValue: number): number => {
  const normalized = stepValue.toString().toLowerCase()
  if (normalized.includes('e-')) {
    return Number(normalized.split('e-')[1])
  }

  const decimals = normalized.split('.')[1]
  return decimals ? decimals.length : 0
}

const roundToDigits = (value: number, digits: number): number => {
  if (digits <= 0) {
    return Math.round(value)
  }

  return Number(value.toFixed(digits))
}

const formatEuropeanNumber = (value: number, fractionDigits: number, useGrouping: boolean): string =>
  new Intl.NumberFormat(EURO_NUMBER_LOCALE, {
    minimumFractionDigits: fractionDigits,
    maximumFractionDigits: fractionDigits,
    useGrouping,
  }).format(value)

function InputField({
  id,
  label,
  value,
  min,
  max,
  step,
  hint,
  fractionDigits,
  useGrouping = false,
  onValueChange,
}: InputFieldProps) {
  const resolvedFractionDigits = fractionDigits ?? countFractionDigits(step ?? 1)
  const [draftValue, setDraftValue] = useState(formatEuropeanNumber(value, resolvedFractionDigits, useGrouping))
  const [isFocused, setIsFocused] = useState(false)
  const holdStartTimeoutRef = useRef<number | null>(null)
  const holdIntervalRef = useRef<number | null>(null)
  const longPressTriggeredRef = useRef(false)
  const activePointerIdRef = useRef<number | null>(null)
  const valueRef = useRef(value)
  const draftValueRef = useRef(draftValue)

  const syncDraftValue = (nextDraftValue: string) => {
    draftValueRef.current = nextDraftValue
    setDraftValue(nextDraftValue)
  }

  const syncValue = (nextValue: number) => {
    valueRef.current = nextValue
    onValueChange(nextValue)
  }

  useEffect(() => {
    valueRef.current = value
  }, [value])

  useEffect(() => {
    if (!isFocused) {
      const formattedValue = formatEuropeanNumber(value, resolvedFractionDigits, useGrouping)
      draftValueRef.current = formattedValue
      setDraftValue(formattedValue)
    }
  }, [isFocused, resolvedFractionDigits, useGrouping, value])

  useEffect(() => {
    return () => {
      if (holdStartTimeoutRef.current !== null) {
        window.clearTimeout(holdStartTimeoutRef.current)
      }

      if (holdIntervalRef.current !== null) {
        window.clearInterval(holdIntervalRef.current)
      }
    }
  }, [])

  const commitValue = (rawValue: string) => {
    if (rawValue === '') {
      syncValue(0)
      return
    }

    const parsedValue = parseEuropeanNumber(rawValue)

    if (Number.isNaN(parsedValue)) {
      return
    }

    const roundedValue = roundToDigits(parsedValue, resolvedFractionDigits)
    const clampedValue = Math.max(min ?? Number.NEGATIVE_INFINITY, Math.min(max ?? Number.POSITIVE_INFINITY, roundedValue))
    syncValue(clampedValue)
  }

  const handleStepChange = (direction: 'increase' | 'decrease') => {
    const increment = step ?? 1
    const parsedDraftValue = parseEuropeanNumber(draftValueRef.current)
    const baseValue = Number.isNaN(parsedDraftValue) ? valueRef.current : parsedDraftValue
    const nextValue = direction === 'increase' ? baseValue + increment : baseValue - increment
    const roundedValue = roundToDigits(nextValue, resolvedFractionDigits)
    const clampedValue = Math.max(min ?? Number.NEGATIVE_INFINITY, Math.min(max ?? Number.POSITIVE_INFINITY, roundedValue))
    syncValue(clampedValue)
    syncDraftValue(formatEuropeanNumber(clampedValue, resolvedFractionDigits, useGrouping))
  }

  const stopContinuousStepChange = () => {
    if (holdStartTimeoutRef.current !== null) {
      window.clearTimeout(holdStartTimeoutRef.current)
      holdStartTimeoutRef.current = null
    }

    if (holdIntervalRef.current !== null) {
      window.clearInterval(holdIntervalRef.current)
      holdIntervalRef.current = null
    }
  }

  const startContinuousStepChange = (direction: 'increase' | 'decrease') => {
    stopContinuousStepChange()
    longPressTriggeredRef.current = false
    holdStartTimeoutRef.current = window.setTimeout(() => {
      longPressTriggeredRef.current = true
      handleStepChange(direction)
      holdIntervalRef.current = window.setInterval(() => {
        handleStepChange(direction)
      }, LONG_PRESS_REPEAT_INTERVAL_MS)
    }, LONG_PRESS_INITIAL_DELAY_MS)
  }

  const handlePressStart = (direction: 'increase' | 'decrease') => {
    startContinuousStepChange(direction)
  }

  const handlePressEnd = (direction: 'increase' | 'decrease') => {
    const shouldApplySingleStep = !longPressTriggeredRef.current
    stopContinuousStepChange()
    longPressTriggeredRef.current = false

    if (shouldApplySingleStep) {
      handleStepChange(direction)
    }
  }

  const createPointerDownHandler = (direction: 'increase' | 'decrease') => (event: PointerEvent<HTMLButtonElement>) => {
    if (event.pointerType === 'mouse' && event.button !== 0) {
      return
    }

    if (activePointerIdRef.current !== null) {
      return
    }

    event.preventDefault()
    activePointerIdRef.current = event.pointerId
    event.currentTarget.setPointerCapture(event.pointerId)
    handlePressStart(direction)
  }

  const createPointerUpHandler = (direction: 'increase' | 'decrease') => (event: PointerEvent<HTMLButtonElement>) => {
    if (activePointerIdRef.current !== event.pointerId) {
      return
    }

    activePointerIdRef.current = null
    handlePressEnd(direction)
  }

  const handlePointerCancel = (event: PointerEvent<HTMLButtonElement>) => {
    if (activePointerIdRef.current !== event.pointerId) {
      return
    }

    activePointerIdRef.current = null
    stopContinuousStepChange()
    longPressTriggeredRef.current = false
  }

  return (
    <label className="block" htmlFor={id}>
      <span className="text-sm font-medium text-slate-200">{label}</span>
      <div className="mt-1 flex gap-2">
        <button
          type="button"
          onPointerDown={createPointerDownHandler('decrease')}
          onPointerUp={createPointerUpHandler('decrease')}
          onPointerCancel={handlePointerCancel}
          className="touch-manipulation rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-lg font-semibold text-slate-100 transition hover:border-emerald-400 hover:text-emerald-300"
          aria-label={`Decrease ${label}`}
        >
          −
        </button>
        <input
          id={id}
          type="text"
          inputMode="decimal"
          className="w-full rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-slate-100 outline-none ring-emerald-400 focus:ring"
          value={draftValue}
          onFocus={() => {
            setIsFocused(true)
            if (parseEuropeanNumber(draftValue) === 0) {
              syncDraftValue('')
            }
          }}
          onBlur={() => {
            setIsFocused(false)
            if (draftValue === '') {
              syncDraftValue(formatEuropeanNumber(0, resolvedFractionDigits, useGrouping))
              return
            }

            const parsedValue = parseEuropeanNumber(draftValue)
            if (Number.isNaN(parsedValue)) {
              syncDraftValue(formatEuropeanNumber(value, resolvedFractionDigits, useGrouping))
              return
            }

            const roundedValue = roundToDigits(parsedValue, resolvedFractionDigits)
            const clampedValue = Math.max(min ?? Number.NEGATIVE_INFINITY, Math.min(max ?? Number.POSITIVE_INFINITY, roundedValue))
            syncValue(clampedValue)
            syncDraftValue(formatEuropeanNumber(clampedValue, resolvedFractionDigits, useGrouping))
          }}
          onChange={(event) => {
            const rawInput = event.target.value
            syncDraftValue(rawInput)
            commitValue(rawInput)
          }}
        />
        <button
          type="button"
          onPointerDown={createPointerDownHandler('increase')}
          onPointerUp={createPointerUpHandler('increase')}
          onPointerCancel={handlePointerCancel}
          className="touch-manipulation rounded-md border border-slate-700 bg-slate-950 px-3 py-2 text-lg font-semibold text-slate-100 transition hover:border-emerald-400 hover:text-emerald-300"
          aria-label={`Increase ${label}`}
        >
          +
        </button>
      </div>
      {hint ? <span className="mt-1 block text-xs text-slate-400">{hint}</span> : null}
    </label>
  )
}

function SummaryItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-slate-700 bg-slate-950/60 p-3">
      <dt className="text-slate-400">{label}</dt>
      <dd className="mt-1 font-semibold text-slate-100">{value}</dd>
    </div>
  )
}

function ChartLegendValue({
  label,
  value,
  colorClassName,
}: {
  label: string
  value: string
  colorClassName: string
}) {
  return (
    <div className="rounded-md border border-slate-700 bg-slate-950/60 p-3">
      <dt className="flex items-center gap-2 text-slate-300">
        <span className={`inline-block h-2.5 w-2.5 rounded-full ${colorClassName}`} aria-hidden />
        <span>{label}</span>
      </dt>
      <dd className="mt-1 font-semibold text-slate-100">{value}</dd>
    </div>
  )
}

function PlanValue({ label, value }: { label: string; value: string }) {
  return (
    <p>
      <span className="text-slate-400">{label}: </span>
      <span className="font-medium text-slate-100">{value}</span>
    </p>
  )
}

export default App
